apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-detector
  namespace: {{ .Values.namespace }}
  labels:
    app: aiops-detector
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: aiops-detector
  template:
    metadata:
      labels:
        app: aiops-detector
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: detector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "src/main.py"]
          envFrom:
            - configMapRef:
                name: aiops-config
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
