apiVersion: v1
kind: ConfigMap
metadata:
  name: aiops-config
  namespace: sre
data:
  PROVIDER: "prometheus"
  PROM_URL: "http://prometheus.monitoring.svc.cluster.local:9090"
  PROM_QUERY: 'rate(container_cpu_usage_seconds_total{namespace="apps"}[2m])'
  STDDEV_MULTIPLIER: "3.0"
  KUBE_NAMESPACE: "sre"
  REMEDIATION_STRATEGY: "generic"
