apiVersion: v1
kind: ServiceAccount
metadata:
  name: aiops-service-account
  namespace: sre
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aiops-role
  namespace: sre
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aiops-rolebinding
  namespace: sre
subjects:
  - kind: ServiceAccount
    name: aiops-service-account
    namespace: sre
roleRef:
  kind: Role
  name: aiops-role
  apiGroup: rbac.authorization.k8s.io
